# Generated by Django 5.1.7 on 2025-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hooks_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('payload', models.TextField(blank=True, null=True)),
                ('requester_ip', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hooks_queue',
                'indexes': [models.Index(fields=['name', 'date_created', 'id'], name='idx_hq_duplicate_check'), models.Index(fields=['date_created'], name='idx_hq_date_created'), models.Index(fields=['payload_hash'], name='idx_hq_payload_hash')],
            },
        ),
    ]
