"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from os import getenv
from pathlib import Path
import os
import sys
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


FRED_API = os.getenv("FRED_API", "https://api.fred.sknv.com")
FRED_PASSWORD_SALT = getenv("FRED_PASSWORD_SALT", "")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("DJANGO_SECRET_KEY", "supersecret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv("APP_ENV", "development") != "production"

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

ALLOWED_HOSTS = ["*"]


# PostHog
POSTHOG_PROJECT_API_KEY = os.getenv("POSTHOG_PROJECT_API_KEY", "") or os.getenv(
    "POSTHOG_API_KEY", ""
)
POSTHOG_HOST = os.getenv("POSTHOG_HOST", "https://us.i.posthog.com")
POSTHOG_ENABLED = bool(POSTHOG_PROJECT_API_KEY)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "storages",
    "mysknv.apps.MysknvConfig",
    "drf_spectacular",
    "core.apps.CoreConfig",
    "fred",
    "tasks",
    "hooks",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if POSTHOG_ENABLED:
    MIDDLEWARE.append("posthog.integrations.django.PosthogContextMiddleware")

POSTHOG = {
    "project_api_key": POSTHOG_PROJECT_API_KEY,
    "host": POSTHOG_HOST,
}

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("DB_NAME", "nextgen"),
        "USER": getenv("DB_USER", "nextgen"),
        "PASSWORD": getenv("DB_PASSWORD", "nextgenpass"),
        "HOST": getenv("DB_HOST", "db"),  # 'db' is the service name from docker-compose
        "PORT": getenv("DB_PORT", "5432"),  # Default PostgreSQL port
    },
    "mysknv": {
        "ENGINE": getenv("FRED_DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": getenv("FRED_DB_NAME", "fred"),
        "USER": getenv("FRED_DB_USER", "fred"),
        "PASSWORD": getenv("FRED_DB_PASSWORD", "supersecret"),
        "HOST": getenv("FRED_DB_HOST", "localhost"),
        "PORT": getenv("FRED_DB_PORT", "5432"),
        "OPTIONS": {"options": "-c search_path=mysknv"},
    },
    "fred": {
        "ENGINE": getenv("FRED_DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": getenv("FRED_DB_NAME", "fred"),
        "USER": getenv("FRED_DB_USER", "fred"),
        "PASSWORD": getenv("FRED_DB_PASSWORD", "supersecret"),
        "HOST": getenv("FRED_DB_HOST", "localhost"),
        "PORT": getenv("FRED_DB_PORT", "5432"),
    },
}

if "test" in sys.argv:
    DATABASES["mysknv"]["OPTIONS"] = {"options": "-c search_path=public"}

CSRF_TRUSTED_ORIGINS = [
    "https://sknv.dev",
    "https://*.sknv.dev",
    "https://app.sknv.com",
    "https://*.elasticbeanstalk.com",
    "https://portal.sknv.dev",
    "https://portal.sknv.com",
    "https://test.fred.sknv.com",
    "https://fred.sknv.com",
    "https://fred.sincerususa.com",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://app.sknv.com",
    "https://portal.sknv.dev",
    "https://portal.sknv.com",
    "https://fred.sknv.com",
    "https://test.fred.sknv.com",
    "https://fred.sincerususa.com",
    "http://localhost:8000",
]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/app\..*\.sknv\.cubby\.zone$",
    r"^https:\/\/my\..*\.sknv\.cubby\.zone$",
    r"^https:\/\/fred\..*\.sknv\.cubby\.zone$",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

DATABASE_ROUTERS = ["core.routers.MultiDBRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

AUTH_USER_MODEL = "core.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "POC API",
    "DESCRIPTION": "POC",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
    # available SwaggerUI configuration parameters
    # https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    # available SwaggerUI versions: https://github.com/swagger-api/swagger-ui/releases
    "SWAGGER_UI_DIST": "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest",  # default
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {
    "heartbeat": {
        "task": "tasks.tasks.betterstack_heartbeat",
        "schedule": crontab(minute="*/1"),  # every minute
    },
    "prometheus_heartbeat": {
        "task": "tasks.tasks.prometheus_heartbeat",
        "schedule": crontab(minute="*/1"),  # every minute
    },
}

if ENVIRONMENT == "production":
    CELERY_BEAT_SCHEDULE.update(
        {
            "close": {
                "task": "tasks.rx.close.run",
                "schedule": crontab(minute="*/10"),
            },
            "update_multiple_patient_queue_status": {
                "task": "tasks.call_queue.tasks.update_multiple_patient_queue_status",
                "schedule": crontab(hour=6, minute=10),
            },
            "cleanup_expired_call_queue_records": {
                "task": "tasks.call_queue.tasks.cleanup_expired_call_queue_records",
                "schedule": crontab(minute="*/2"),
            },
            "populate_patient_call_queue": {
                "task": "tasks.call_queue.tasks.populate_patient_call_queue",
                "schedule": crontab(hour=6, minute=0),
            },
            "update_resolved_payment_holds": {
                "task": "tasks.call_queue.tasks.update_resolved_payment_holds",
                "schedule": crontab(minute="*/10"),
            },
            "release_expired_on_hold_records": {
                "task": "tasks.call_queue.tasks.release_expired_on_hold_records",
                "schedule": crontab(minute="*/10"),
            },
            "twilio": {
                "task": "tasks.twilio.tasks.pull_twilio_messages_to_s3",
                "schedule": crontab(hour=6, minute=0),
            },
            "md_prescriptions": {
                "task": "tasks.md_prescriptions.tasks.import_prescription_dispenses_from_db_task",
                "schedule": crontab(hour=10, minute=0),
            },
            "call_queue_process_patient_outreach_records": {
                "task": "tasks.call_queue.tasks.process_patient_outreach_records",
                "schedule": crontab(minute="*/2"),
            },
            "hubspot_fred_sync": {
                "task": "tasks.hubspot.tasks.run_hubspot_sync_pipeline",
                "schedule": crontab(hour=5, minute=0),
            },
        }
    )

if ENVIRONMENT == "test":
    CELERY_BEAT_SCHEDULE.update(
        {
            "call_queue_process_patient_outreach_records": {
                "task": "tasks.call_queue.tasks.process_patient_outreach_records",
                "schedule": crontab(minute="*/2"),
            },
        }
    )

if ENVIRONMENT == "development":
    CELERY_BEAT_SCHEDULE.update(
        {
            "call_queue": {
                "task": "tasks.call_queue.tasks.update_resolved_payment_holds",
                "schedule": crontab(minute="*/10"),
            },
            "call_queue_process_patient_outreach_records": {
                "task": "tasks.call_queue.tasks.process_patient_outreach_records",
                "schedule": crontab(minute="*/2"),
            },
        }
    )

if ENVIRONMENT == "dev":
    CELERY_BEAT_SCHEDULE.update(
        {
            "call_queue": {
                "task": "tasks.call_queue.tasks.update_resolved_payment_holds",
                "schedule": crontab(minute="*/10"),
            },
            "call_queue_process_patient_outreach_records": {
                "task": "tasks.call_queue.tasks.process_patient_outreach_records",
                "schedule": crontab(minute="*/2"),
            },
        }
    )

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

EMAIL_BACKEND = "django_ses.SESBackend"
AWS_SES_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_SES_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SES_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")

DH_APP_URL = os.environ.get("DH_APP_URL", "")
INTERNAL_TOKEN = os.environ.get("INTERNAL_TOKEN", "")
API_DOMAIN = os.environ.get("API_DOMAIN", "")

DIGITAL_HEALTH_API_URL = os.environ.get("DIGITAL_HEALTH_API_URL", "http://localhost:3001")
DIGITAL_HEALTH_API_TOKEN = os.environ.get(
    "DIGITAL_HEALTH_API_TOKEN",
    "wrPZ36V62YNNXz1trNbwNFWAv6BxAmgsdOrEkpPbMO6OFfJ63Uifa1RFXW49mHfY",
)

HUBSPOT_ACCESS_TOKEN = os.environ.get("HUBSPOT_ACCESS_TOKEN", "")
HUBSPOT_DEBUG = False

CYBERSOURCE_MERCHANT_ID = os.environ.get("CYBERSOURCE_MERCHANT_ID", "your_merchant_id")
CYBERSOURCE_MERCHANT_KEY_ID = os.environ.get(
    "CYBERSOURCE_MERCHANT_KEY_ID", "your_key_id"
)
CYBERSOURCE_MERCHANT_SECRET_KEY = os.environ.get(
    "CYBERSOURCE_MERCHANT_SECRET_KEY", "your_secret_key"
)
CYBERSOURCE_ENVIRONMENT = os.environ.get("CYBERSOURCE_ENVIRONMENT", "production")

CELERY_BETTERSTACK_HEARTBEAT_URL = os.environ.get(
    "CELERY_BETTERSTACK_HEARTBEAT_URL",
    "https://uptime.betterstack.com/api/v1/heartbeat/nBwkALcPpTjqQwJvrP3osLNj",
)

PROMETHEUS_REMOTE_WRITE_URL = os.environ.get("PROMETHEUS_REMOTE_WRITE_URL", "")
PROMETHEUS_REMOTE_WRITE_REGION = os.environ.get(
    "PROMETHEUS_REMOTE_WRITE_REGION",
    os.environ.get("AWS_REGION", os.environ.get("AWS_DEFAULT_REGION", "")),
)
PROMETHEUS_REMOTE_WRITE_TIMEOUT = int(
    os.environ.get("PROMETHEUS_REMOTE_WRITE_TIMEOUT", "5")
)
