# Generated by Django 5.1.7 on 2025-08-07 13:43

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    Role.objects.get_or_create(name="admin")


def remove_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    Role.objects.filter(name="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_role_user_roles"),
    ]

    operations = [
        migrations.RunPython(add_roles, reverse_code=remove_roles),
    ]
