# Generated by Django - add this to your core/migrations/ directory

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_patient_outreach_group(apps, schema_editor):
    """
    Create a permission group with access to:
    - patient_outreach_detail (view PatientOutreach)
    - patient_outreach_list (view PatientOutreach)
    - patient_outreach_create (add PatientOutreach)
    - update_patient_call_queue (change PatientCallQueue)
    """
    # Get or create the group
    group, created = Group.objects.get_or_create(name="Patient Outreach Staff")

    if created:
        print(f"✓ Created new group: '{group.name}'")
    else:
        print(f"✓ Group '{group.name}' already exists, updating permissions...")

    # Get content types by app_label and model name
    # This avoids needing the actual model class during migration
    try:
        outreach_content_type = ContentType.objects.get(
            app_label="fred", model="patientoutreach"
        )
        call_queue_content_type = ContentType.objects.get(
            app_label="fred", model="patientcallqueue"
        )
    except ContentType.DoesNotExist:
        print(
            "⚠ Warning: Content types not found. Models may need to be created first."
        )
        return

    # Define the permissions we need
    permissions_to_add = []

    # PatientOutreach permissions
    # - view_patientoutreach: allows access to detail and list endpoints
    # - add_patientoutreach: allows access to create endpoint
    outreach_permissions = Permission.objects.filter(
        content_type=outreach_content_type,
        codename__in=["view_patientoutreach", "add_patientoutreach"],
    )
    permissions_to_add.extend(list(outreach_permissions))

    # PatientCallQueue permissions
    # - view_patientcallqueue: allows viewing queue records
    # - change_patientcallqueue: allows updating queue records via update_patient_call_queue endpoint
    call_queue_permissions = Permission.objects.filter(
        content_type=call_queue_content_type,
        codename__in=["view_patientcallqueue", "change_patientcallqueue"],
    )
    permissions_to_add.extend(list(call_queue_permissions))

    # Clear existing permissions and add new ones
    group.permissions.clear()
    for permission in permissions_to_add:
        group.permissions.add(permission)
        print(f"  ✓ Added permission: {permission.codename}")

    print(
        f"\n✓ Successfully configured group '{group.name}' with {len(permissions_to_add)} permissions"
    )


def remove_patient_outreach_group(apps, schema_editor):
    """
    Remove the patient outreach group (reverse operation)
    """
    deleted_count, _ = Group.objects.filter(name="Patient Outreach Staff").delete()
    if deleted_count > 0:
        print(f"✓ Removed group 'Patient Outreach Staff'")
    else:
        print("✗ Group 'Patient Outreach Staff' not found")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_initial_roles"),
    ]

    operations = [
        migrations.RunPython(
            create_patient_outreach_group, reverse_code=remove_patient_outreach_group
        ),
    ]
